seed_everything: 42
trainer:
  max_epochs: 30
  accelerator: "gpu"
  devices: 2
  
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        save_weights_only: false
        mode: "min"
        monitor: "val_loss"
        every_n_train_steps: 0
        every_n_epochs: 1
        save_top_k: 1
        filename: "best_checkpoint"
        verbose: True
        train_time_interval: null


    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: "val_loss"
        min_delta: 0.0
        patience: 5
        verbose: False


    - class_path: lightning.pytorch.callbacks.TQDMProgressBar
      init_args:
        refresh_rate: 1
        leave: True


  logger:
    - class_path: lightning.pytorch.loggers.TensorBoardLogger
      init_args:
        save_dir: "."
        name: "Top_checkpoints"

model:
  class_path: source.GCN_network.GCNModel
  init_args:
    In_feat: 10
    H_feat: 64
    Num_classes: 1
    num_layers: 8
    num_heads: 32
    dropout: 0.2
    lr : 0.0005

data:
  class_path: data_handeling.data_handeling_GCN.CustomDataModule
  init_args:
    dir_: "/data1/hammad/tqgamma/data_transformer/data/"
    n_event: 1200_000    
    batch_size: 1028
